ENABLE_DEBUG = False

ENDING_POSITION = 1.0
AVERAGE_TIME = 30
IP = '192.168.0.3'
##IP = '...'
PORT = 1996
CLIENT_LIMIT = 6
PLAYER_LIMIT = 3
LAUNCH_TIME = 6.5
AVERAGE_FREQUENCY = 5

FREQ_TO_VELOCITY = 10 * ENDING_POSITION / AVERAGE_TIME / AVERAGE_FREQUENCY

BROADCAST_DELAY = 0.05
