ENABLE_DEBUG = True

ENDING_POSITION = 1.0
AVERAGE_TIME = 180
PORT = 1995
CLIENT_LIMIT = 6
PLAYER_LIMIT = 3
AVERAGE_FREQUENCY = 5

FREQ_TO_VELOCITY = ENDING_POSITION / AVERAGE_TIME / AVERAGE_FREQUENCY

POSITION_LIMIT = 1/180 # not in use
